FORMAT: 1A
HOST: https://makeyourfrete.com/api/v1

# MakeYourFrete Core API

# Group Admins
Grupo de recursos dos perfis administrativos.

## Conta Administrativa [/admins]
<!-- include(resources/post-admins.md) -->

## Autenticação [/admins/auth]
<!-- include(resources/get-admin-auth.md) -->



# Group Workers
Grupo de recursos dos perfis de motoristas.

## Conta do Motorista [/workers]
<!-- include(resources/post-workers.md) -->

## Autenticação [/workers/auth]
<!-- include(resources/get-worker-auth.md) -->



# Group Companies
Grupo de recursos dos perfis corporativos.

## Conta da Empresa [/companies]
<!-- include(resources/post-companies.md) -->

## Autenticação [/companies/auth]
<!-- include(resources/get-company-auth.md) -->



# Group Proposals
Grupo de recursos das propostas de corrida.

## Criação e Listagem de Propostas [/proposals]
<!-- include(resources/post-proposals.md) -->
<!-- include(resources/get-proposals.md) -->

## Proposta [/proposals/{uid}]

+ Parameters

    + uid:`123` (required, int) - O identificador único da proposta.

<!-- include(resources/get-proposal-by-id.md) -->

## Oferta de Valor em Proposta [/proposals/{uid}/offers]

+ Parameters

    + uid:`123` (required, int) - O identificador único da proposta.

<!-- include(resources/post-proposal-offer.md) -->
