FORMAT: 1A
HOST: https://makeyourfrete.com/api/v1

# MakeYourFrete Core API

# Group Admins
Grupo de recursos dos perfis administrativos.

## Conta Administrativa [/admins]
<!-- include(resources/admins/post-admins.md) -->

## Administrador [/admins/{uid}]

+ Parameters

    + uid:`123` (required, int) - Identificador único do administrador.

<!-- include(resources/admins/get-admin-by-id.md) -->

## Autenticação [/admins/auth]
<!-- include(resources/admins/get-admin-auth.md) -->



# Group Workers
Grupo de recursos dos perfis de motoristas.

## Conta do Motorista [/workers]
<!-- include(resources/workers/post-workers.md) -->

## Autenticação [/workers/auth]
<!-- include(resources/workers/get-worker-auth.md) -->

## Motorista [/workers/{uid}]

+ Parameters

    + uid:`123` (required, int) - Identificador único do motorista.

<!-- include(resources/workers/get-worker-by-id.md) -->

## Ofertas do Motorista [/workers/{uid}/offers]

+ Parameters

    + uid:`123` (required, int) - Identificador único do motorista.

<!-- include(resources/workers/get-worker-offers.md) -->



# Group Companies
Grupo de recursos dos perfis corporativos.

## Conta da Empresa [/companies]
<!-- include(resources/companies/post-companies.md) -->

## Autenticação [/companies/auth]
<!-- include(resources/companies/get-company-auth.md) -->

## Empresa [/companies/{uid}]

+ Parameters

    + uid:`123` (required, int) - Identificador único da empresa.

<!-- include(resources/companies/get-company-by-id.md) -->

## Propostas da Empresa [/companies/{uid}/proposals]

+ Parameters

    + uid:`123` (required, int) - Identificador único da empresa.

<!-- include(resources/companies/get-company-proposals.md) -->



# Group Proposals
Grupo de recursos das propostas de corrida.

## Criação e Listagem de Propostas [/proposals]
<!-- include(resources/proposals/post-proposals.md) -->
<!-- include(resources/proposals/get-proposals.md) -->

## Proposta [/proposals/{uid}]

+ Parameters

    + uid:`123` (required, int) - Identificador único da proposta.

<!-- include(resources/proposals/get-proposal-by-id.md) -->

## Oferta de Valor em Proposta [/proposals/{uid}/offers]

+ Parameters

    + uid:`123` (required, int) - Identificador único da proposta.

<!-- include(resources/proposals/post-proposal-offer.md) -->
