FORMAT: 1A
HOST: https://makeyourfrete.com/api/v1

# MakeYourFrete Core API



# Data Structures



# Group Admins
Grupo de recursos dos perfis administrativos.

## Conta Administrativa [/admins]
### Cadastra Novo Administrador [POST]


## Autenticação [/admins/auth]
### Autentica Conta Administrativa [GET]

+ Request with body (application/json)

    + Body

            <!-- include(requests/admin-auth.json) -->

+ Response 200 (application/json)

    + Body

            <!-- include(responses/authenticated.json) -->

+ Response 400 (application/json)

    + Body

            <!-- include(responses/invalid-request.json) -->

+ Response 403 (application/json)

    + Body

            <!-- include(responses/incorrect-email-or-password.json) -->



# Group Workers
Grupo de recursos dos perfis de motoristas.

## Conta do Motorista [/workers]
### Cadastra Novo Motorista [POST]


## Autenticação [/workers/auth]
### Autentica Conta do Motorista [GET]

+ Request with body (application/json)

    + Body

            <!-- include(requests/worker-auth.json) -->

+ Response 200 (application/json)

    + Body

            <!-- include(responses/authenticated.json) -->

+ Response 400 (application/json)

    + Body

            <!-- include(responses/invalid-request.json) -->

+ Response 403 (application/json)

    + Body

            <!-- include(responses/incorrect-email-or-password.json) -->



# Group Companies
Grupo de recursos dos perfis corporativos.

## Conta do Motorista [/workers]
### Cadastra Novo Motorista [POST]


## Autenticação [/workers/auth]
### Autentica Conta do Motorista [GET]

+ Request with body (application/json)

    + Body

            <!-- include(requests/company-auth.json) -->

+ Response 200 (application/json)

    + Body

            <!-- include(responses/authenticated.json) -->

+ Response 400 (application/json)

    + Body

            <!-- include(responses/invalid-request.json) -->

+ Response 403 (application/json)

    + Body

            <!-- include(responses/incorrect-email-or-password.json) -->



# Group Proposals
Grupo de recursos das propostas de corrida.

## Proposta de corrida [/proposals]

### Cadastra Nova Proposta [POST]
### Lista Propostas Abertas [GET]
